[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bridge_program = "28AQpwDXyQPTkcuJweUQFfAMqTkDZfNME71Anic7o5rM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
