[toolchain]
channel = "1.82.0"
components = ["rustc", "cargo", "rustfmt"]
anchor_version = "0.29.0"


[features]
resolution = true
skip-lint = false

[programs.devnet]
bridge_program = "911VdUg43JGvomS2eCqKHJcUZ6J9SCjb371w6Xst7YMD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[source.crates-io]
replace-with = 'default' 


[source.default]
registry = "https://github.com/rust-lang/crates.io-index"



[scripts]
test = "cargo test" 

