[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.8.0", features = ["csr"] }
solana-program = "1.16.0"
log = "0.4"  
wasm-bindgen = "0.2"  
js-sys = "0.3.77"
