[package]
name = "relayer-bot"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.36", features = ["full"] }
anchor-client = "0.27.0"
ethers = { version = "2.0", features = ["abigen", "ws"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }